# Why we add this file https://yarnpkg.com/features/pnp
# Remember that migrating to Yarn PnP is optional: you can revert to node_modules installs at any time 
# by setting the nodeLinker: node-modules setting in your project's .yarnrc.yml file.
# Fixes "Cannot find module 'react' or its corresponding type declarations" error

nodeLinker: node-modules